apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: golang-http-merge-request
spec:
  pipelineSpec:
    params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.
    tasks:
      - name: "git-clone"
        taskRef:
          name: "https://raw.githubusercontent.com/tektoncd/catalog/master/task/git-clone/0.3/git-clone.yaml"
        params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
  params:
  - name: repo-url
    value: {{{ .repository.url }}}
  - name: branch-name
    value: {{{ .repository.branch }}}

          
