apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: "{{ .Name }}-push"
spec:
  pipelineSpec:
    workspaces:
    - name: "{{ .Name }}-workspace"
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task.
    params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.
    tasks:
      - name: "git-clone"
        taskRef:
          name: "https://raw.githubusercontent.com/tektoncd/catalog/master/task/git-clone/0.3/git-clone.yaml"
        params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
        workspaces:
        - name: output
          workspace: "{{ .Name }}-workspace"
      - name: "golang-default-quality"
        runAfter: ["git-clone"]
        taskRef:
          name: "https://raw.githubusercontent.com/maycommit/tasks/master/golang-default-quality/task.yaml"
        workspaces:
        - name: source
          workspace: "{{ .Name }}-workspace"
  params:
  - name: repo-url
    value: {{ .RepositoryURL }}
  - name: branch-name
    value: {{ .Branch }}

